### PR TITLE
add code without coverage to verify that a decrease in coverage fails the build

### PR DESCRIPTION
**Pull request by m-mcgowan**

### CODE REVIEW

**Comment by m-mcgowan** [comment]
I think it's about as good as we can get it considering the uphill climb it's been to get this far. I'd like to merge it and gain some experience with how well it works and then make adjustments as necessary.

**Comment by zfields** [comment]
I'll review it today.

**Comment by zfields** [comment]
I spent the better part of the day reviewing the PR and understanding the short-comings of the official Coveralls GitHub Action...

The official Coveralls GitHub Action does not distinguish between the Docker action file system, VM action file system and native GitHub runner file system.

By updating the file paths in the `lcov` file, I was able to eliminate a significant portion of our CI infrastructure and simplify the implementation. That research spike is captured in #67.

I propose closing this PR and adopting #67 instead.

**Review by zfields — CHANGES_REQUESTED** [review]
Propose migrating to alternate solution.

**Comment by zfields** [comment]
Closed in favor of #67

**Pull request closed without merging**
